// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fxivxhxjjpaollcgnnsv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ4aXZ4aHhqanBhb2xsY2dubnN2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwOTAxMDMsImV4cCI6MjA2MzY2NjEwM30.r7TEEF983lL70NH-E7SIZZwv_dwkgYe7IIr6JG7-JsA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);